Bla/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('gallery/', include('gallery.urls', namespace='gallery'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from . import views

from django.urls import path, include

app_name='blog'

urlpatterns = [
    path('', views.post_list),
    path('post/<int:pk>/', views.viv_post),
    path('post/add_post/', views.add_post, name='add_post'),
]

gallery/urls.py
from . import views

from django.urls import path

app_name='gallery'

urlpatterns = [
    path('', views.foto_gallery, name='foto_gallery'),
    path('foto/<int:pk>', views.foto_foto, name='foto_foto'),
]

blog/models.py
from django.db import models

from django.conf import settings

from django.utils import timezone


class Tag(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=50)
    txt=models.TextField()
    #published_date=models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(blank=True, null=True)
    published_date=models.DateTimeField(default=timezone.now)
    autor=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tags=models.ManyToManyField(Tag, null=True)

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def __str__(self):
        return self.title

gallery/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from blog.models import Tag

class Gallery(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=200)
    published_date = models.DateTimeField(default=timezone.now)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, null=True)
    def __str__(self):
        return self.title

class Foto(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='gallery/')
    description = models.TextField(verbose_name='description/', null=True)
    def __str__(self):
        return self.gallery.title+'foto'

blog/forms.py
from django import forms
from .models import Post, Tag

class NewPostForms(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=Post

blog/views.py
from django.http import  HttpResponseRedirect
from django.shortcuts import render, reverse
from django.utils import timezone
from .models import Post
from .forms import NewPostForms
from .forms import NewPostForms

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def viv_post(request, pk):
    my_post = Post.objects.get(pk=pk)
    return render(request, 'blog/viv_post.html', {'post':my_post})

def add_post(request):
    if request.method == 'GET':
        form = NewPostForms().as_p()
        return render(request, 'blog/add_post.html', {"form":form})
    elif request.method=="POST":
        NewPostForms(request.POST).save()
        return HttpResponseRedirect(reverse("blog:add_post"))

gallery/views.py
from django.shortcuts import render, get_object_or_404
from gallery import *
from .models import Gallery

def foto_gallery(request):
    gallerys = Gallery.objects.all()
    return render(request, 'gallery/gallery.html', {'gallerys':gallerys})

def foto_foto(request, pk):
    foto = get_object_or_404(Gallery, pk=pk)
    return render(request, 'gallery/foto.html', {'foto':foto})

blog/templates/blog/add_post.html
{% extends 'blog/post_list.html' %}
{% block content %}
<form method="post" action="{% url 'blog:add_post' %}">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Submit">
</form>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Kristallik</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        {% block main %}
        {% endblock %}
    </body>
</html>

blog/templates/blog/footer.html
<footer>
    <div class="ftr">
        <p class="ftr">подвальчик, пока фз что тут будет:)</p>
        <p class="ftr">Наверное сделаю тут пару ссылок на сайты, чисто для себя) НП:</p>
        <a href="https://htmlacademy.ru">HTML Academy</a>
    </div>
</footer>

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
         <div class="page-header">
             <div class="kristall">
                 <h1><a href="/">Kristallik</a></h1>
             </div>
             <div class="cons">
                 <div id="clock">
                     <div id="hour"><img src="{% static 'image/hours.png' %}"></div>
                     <div id="minute"><img src="/images/minutes"></div>
                     <div id="second"><img src="/images/seconds"></div>
                 </div>
                 <h1><a href="{% url 'blog:add_post' %}">Конст</a></h1>
             </div>
         </div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="nav">
                <div class="gabriola">
                    <p>Навигация</p>
                </div>
                <nav>
                    <div reversed type="I">
                        {% for post in posts reversed %}
                            <li><a href="post/{{ post.pk }}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ol>
                </nav>
            </div>
        </div>
        <div class='col-md-8'>
            <div class="content">
                {% block content %}
                    {% for post in posts reversed %}
                         <div class="postli">
                             <div class="post">
                                 <h2><a href="post/{{ post.pk }}">{{ post.title }}</a></h2>
                                 <p>{{ post.txt }}</p>
                                 <p>Теги: {%if post.tags %}{{ post.tags }} {%else%} нетути {%endif%}</p>
                                 <p>Автор:{{ post.autor }}</p>
                                 <div class="date">
                                     <p>Дата Создания:{{ post.created_date }} Дата публикации: {{ post.published_date }}</p>
                                 </div>
                             </div>
                         </div>
                    {% endfor %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
<footer class="container">
    <div class="row">
        <div class="col align-self-end">
            {% include 'blog/footer.html' %}
            <p><a href="post/add_post/">Конст</a></p>
        </div>
    </div>
</footer>
{% endblock %}

blog/templates/blog/viv_post.html
{% extends 'blog/base.html' %}
{% block main %}
         <div class="page-header">
             <h1><a href="/">{{ post.title }}</a></h1>
         </div>
<div class="content">
         <div class="post">
             <h2>{{ post.title }}</a></h2>
             <p>{{ post.txt }}</p>
             <p>Теги: {%if post.tags %}{{ post.tags }} {%else%} нетути {%endif%}</p>
             <p>Автор:{{ post.autor }}</p>
             <div class="date">
                 <p>Дата Создания:{{ post.created_date }} Дата публикации: {{ post.published_date }}</p>
             </div>
         </div>
</div>
{% endblock %}

gallery/templates/gallery/base_gallery.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Kristallik</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        {% block main %}
        {% endblock %}
    </body>
</html>

gallery/templates/gallery/foto.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col align-self-center">
            <div class="pageimage-header">
                <h1>{{ foto.title }}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="textImage">
                <p class="text-mutted">{{ foto.text }}</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="container1">
                <div class="imImage">
                    {% for f in foto.foto_set.all %}
                    <div class="OneIm">
                        <img src="/media/{{ f.foto }}">
                        <div class="descIm">
                            <p class="white">{{ f.description }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

gallery/templates/gallery/gallery.html
{% extends 'base.html' %}
{% block main %}
<div class="nav">
    <div class="container" >
        <div class="row">
            <div class="col-md-4">
                <h2>Навигация</h2>
                <div class="list-group">
                    {% for gal in gallerys %}
                    <a class='white' href="foto/{{ gal.pk }}">{{ gal.title }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Kristallik</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
         <div class="page-header">
             <h1><a href="/">Kristallik</a></h1>
             <h1 class="cons"><a href="{% url 'blog:add_post' %}">Конст</a></h1>
         </div>
        {% block main %}
        {% endblock %}
    </body>
</html>